package com.sevenwonders.management.domain.card.events;

public enum EventsEnum {
  CHECKED_CONSTRUCTION,
  CHECKED_REQUIREMENT,
  DISCARDED_CONSTRUCTION,
  SELECTED_CARD,
  UPDATED_REQUIREMENT,
  VALIDATED_CONSTRUCTION,
  VALIDATED_REQUIREMENT,
  DISCARDED_CARD,
}
